version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/quizfeed/
hooks:
  BeforeInstall:
    - location: scripts/cleanup
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/restart_server
      timeout: 300
      runas: root
